baseURL = "https://bcdrworkshop.lab798.com/"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ali Speedy Migration workshop"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/hansijie/ASM-Workshop/edit/master/content/"
  themeVariant = "mine"
  showVisitedLinks = false
  author = "Han Sijie<sijie@amazon.com>"
  description = "如何从阿里云迁移到AWS云"
  disableSearch = false
  disableAssetsBusting = false
  disableShortcutsTitle = true
  branch = "master"
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"
  codeRepoName = "hansijie/ASM-Workshop"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/hansijie/ASM-Workshop"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/hansijie/ASM-Workshop/issues"
weight = 40

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]