AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC Resource
Parameters:
  VpcCidr:
    Description: The VPC CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SubnetCidr1:
    Description: The Public Subnet CIDR in cn-northwest-1a
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SubnetCidr2:
    Description: The Public Subnet CIDR in cn-northwest-1b
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.32.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SubnetCidr3:
    Description: The Private Subnet CIDR in cn-northwest-1a
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.64.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SubnetCidr4:
    Description: The Private Subnet CIDR in cn-northwest-1b
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.96.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DBName:
    Default: wordpressdb
    Description: The WordPress database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The WordPress database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9_\\-]*"
    ConstraintDescription: must contain only alphanumeric characters.
  KeyPairName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair
  EC2InstancePrivateIP:
    Description: Private IP Address
    Type: String
    Default: 10.0.0.5
Resources:
  BCDRVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: ALIMIGRATIONVPC
  WordpressSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: !Ref SubnetCidr1
      MapPublicIpOnLaunch : true
      Tags:
        - Key: Name
          Value: ALIMIGRATIONDMZSubnet1
      VpcId: !Ref BCDRVPC
  WordpressSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: !Ref SubnetCidr2
      MapPublicIpOnLaunch : true
      Tags:
        - Key: Name
          Value: ALIMIGRATIONDMZSubnet2
      VpcId: !Ref BCDRVPC
  WordpressSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: !Ref SubnetCidr3
      Tags:
        - Key: Name
          Value: ALIMIGRATIONPrivateSubnet1
      VpcId: !Ref BCDRVPC
  WordpressSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: !Ref SubnetCidr4
      Tags:
        - Key: Name
          Value: ALIMIGRATIONPrivateSubnet2
      VpcId: !Ref BCDRVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: WordpressInternetGateway
  VPCGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref BCDRVPC
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BCDRVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  WordPressSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref WordpressSubnet1
  WordPressSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref WordpressSubnet2
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BCDRVPC
  WordPressSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref WordpressSubnet3
  WordPressSubnet4RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref WordpressSubnet4
  # NatGateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - EIP
        - AllocationId
      SubnetId: !Ref WordpressSubnet1
      Tags:
      - Key: Name
        Value: NatGateway
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  VPNInstanceRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 192.168.0.0/16
      InstanceId: !Ref BastionVPNEC2Instance

  VPNInstanceRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 192.168.0.0/16
      InstanceId: !Ref BastionVPNEC2Instance

  BastionVPNSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn: BCDRVPC
    Properties:
      GroupDescription: BastionHost - 22/ssh, 500/4500/openvpn
      VpcId: !Ref BCDRVPC
      Tags:
        - Key: Name
          Value: SGBastionVPN
      SecurityGroupIngress:
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 192.168.0.0/16
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: for ssh
        - IpProtocol: udp
          FromPort: 500
          ToPort: 500
          CidrIp: 0.0.0.0/0
          Description: for openvpn
        - IpProtocol: udp
          FromPort: 4500
          ToPort: 4500
          CidrIp: 0.0.0.0/0
          Description: for openvpn
  InstanceNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: ENI
      SubnetId: !Ref WordpressSubnet1
      PrivateIpAddress: !Ref EC2InstancePrivateIP
      GroupSet: 
        - !Ref BastionVPNSecurityGroup
      Tags:
        - Key: Name
          Value: Bastion ENI

  BastionVPNEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-07172dea9a75e2143
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref InstanceNetworkInterface
          DeviceIndex: 0
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 20
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: BastionInstance
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          # Updates & Install needed programs
          yum update -y 

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-WebServer
      GroupDescription: Security Group for WebServer
      VpcId: !Ref BCDRVPC
      SecurityGroupIngress:
      - IpProtocol: '-1'
        FromPort: '-1'
        ToPort: '-1'
        CidrIp: 192.168.0.0/16
      - IpProtocol: '-1'
        FromPort: '-1'
        ToPort: '-1'
        CidrIp: !Ref VpcCidr
  BasionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-Basion
      GroupDescription: Enable Basion Login from Internet
      VpcId: !Ref BCDRVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3389'
        ToPort: '3389'
        CidrIp: '0.0.0.0/0'
  SGDataBaseLogin:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-Database
      GroupDescription: Security Group for login DataBase
      SecurityGroupIngress:
        - CidrIp: !Ref VpcCidr
          Description: MYSQL Login
          FromPort: 3306
          IpProtocol: TCP
          ToPort: 3306
        - CidrIp: 192.168.0.0/16
          Description: MYSQL Login
          FromPort: 3306
          IpProtocol: TCP
          ToPort: 3306
      Tags:
        - Key: Name
          Value: SecurityGroup For Database Login
      VpcId: !Ref BCDRVPC


# DMS
  DMSReplicationInstance:
    Type: "AWS::DMS::ReplicationInstance"
    Properties:
      AllocatedStorage: 100
      ReplicationInstanceClass: dms.c4.large
      ReplicationInstanceIdentifier: bcdrdms
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup
      Tags:
        - Key: Name
          Value: bcdr-dms-replicationinstance
      VpcSecurityGroupIds:
        - !Ref SGDataBaseLogin
        - !Ref WebServerSecurityGroup
  ReplicationSubnetGroup:
    Type: "AWS::DMS::ReplicationSubnetGroup"
    Properties:
      ReplicationSubnetGroupDescription: DMSSubnetsGroup
      ReplicationSubnetGroupIdentifier: DMSSubnetsGroup
      SubnetIds:
        - !Ref WordpressSubnet1
        - !Ref WordpressSubnet2
        - !Ref WordpressSubnet3
        - !Ref WordpressSubnet4
      Tags:
        - Key: Name
          Value: RepInstanceSubnetGroup

# RDS
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: DBParameterGroup for wordpress
      Family: mysql5.7
      Parameters:
        character_set_client: utf8
        character_set_connection: utf8
        character_set_database: utf8
        character_set_filesystem: utf8
        character_set_results: utf8
        character_set_server: utf8
        collation_connection: utf8_general_ci
        collation_server: utf8_general_ci
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: wordpress db subnet group
      DBSubnetGroupName: string
      SubnetIds:
        - !Ref WordpressSubnet1
        - !Ref WordpressSubnet2
        - !Ref WordpressSubnet3
        - !Ref WordpressSubnet4
  DataBase:
    DependsOn:
      - DBParameterGroup
      - DBSubnetGroup
    DeletionPolicy: Delete
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.r4.large
      DBInstanceIdentifier: wordpress
      DBName: !Ref DBName
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeleteAutomatedBackups: False
      DeletionProtection: False
      Engine: mysql
      EngineVersion: 5.7.26
      MasterUserPassword: !Ref DBPassword
      MasterUsername: !Ref DBUser
      MultiAZ: False
      PubliclyAccessible: False
      StorageType: gp2
      Tags:
        - Key: Name
          Value: wordpress-database
      VPCSecurityGroups:
        - !Ref SGDataBaseLogin

